# week08/k8s/configmaps.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-config-w08e1
data:
  # Database Names
  PRODUCTS_DB_NAME: products
  ORDERS_DB_NAME: orders
  AZURE_STORAGE_CONTAINER_NAME: product-images
  AZURE_SAS_TOKEN_EXPIRY_HOURS: "24"

  PRODUCT_SERVICE_URL: "http://product-service-w08e1:8000"
  ORDER_SERVICE_URL: "http://order-service-w08e1:8001"