# week08/k8s/frontend.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config
            items:
              - key: config.js
                path: config.js
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w08e1
  labels: { app: frontend }
spec:
  selector: { app: frontend }
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
